DEFAULT_INTERVAL = 5
DEFAULT_SHOW_VOLUME = False

MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 30
MARKET_CLOSE_HOUR = 15
MARKET_CLOSE_MINUTE = 0
MARKET_LUNCH_START_HOUR = 11
MARKET_LUNCH_START_MINUTE = 30
MARKET_LUNCH_END_HOUR = 13
MARKET_LUNCH_END_MINUTE = 0
